### ISSUE TITLE
ERRO[0088] error syncing key (my-spring-app/my-spring-boot): PersistentVolumeClaim "m2-data" is invalid: metadata.namespace: Required value

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/component-operator#1]
## Issue

When the obj is created, then no namespace is set ....

https://goo.gl/PnirWd

![screenshot 2018-10-04 19 52 35](https://user-images.githubusercontent.com/463790/46492894-283dbf00-c80f-11e8-9cfe-33a396c05fad.png)

## To Debug

- Start minishift 3.10, create a project -> "my-spring-app"
- Start the go in debug mode -> `OPERATOR_NAME=component-operator;WATCH_NAMESPACE=my-spring-app;KUBERNETES_CONFIG=/Users/dabou/.kube/config $GOPATH/src/github.com/snowdrop/component-operator/cmd/component-operator/main.go`
- Install resources
```
oc create -f deploy/sa.yaml
oc create -f deploy/rbac.yaml
oc create -f deploy/crd.yaml
```
- Deploy a CRD -> `oc apply -f deploy/component1.yml`

**Comment by geoand** [comment]
Can you please provide more information on how to reproduce the issue?

**Comment by geoand** [comment]
Thanks

**Comment by geoand** [comment]
Interesting fix :)
