### ISSUE TITLE
Normal user can't create a Component CRD

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/component-operator#13]
This is the error that we get when we try to apply the backend demo .yml when logged with developer's  user :

```
$ oc apply -f fruit-backend/component.yml
Error from server (Forbidden): error when retrieving current configuration of:
&{0xc420ca6cc0 0xc4202c2e00 my-spring-app fruit-backend fruit-backend/component.yml 0xc4226bb850  false}
from server for: "fruit-backend
/component.yml": components.component.k8s.io "fruit-backend" is forbidden:
 User "developer" cannot get components.component.k8s.io in the namespace "my-spring-app":
 no RBAC policy matched
```

**Comment by quintesse** [comment]
I followed the exact [Setup](https://github.com/snowdrop/component-operator-demo#setup) instructions. But for [Demo's time](https://github.com/snowdrop/component-operator-demo#demos-time) I switched to "developer". That's the only thing I did that wasn't in the docs

Using Minishift 1.27.0 with OKD 3.11.0

**Comment by cmoulliard** [comment]
I need to modify or add another clusterrole which allows that a user having `view` role can process it : https://docs.okd.io/latest/admin_guide/custom_resource_definitions.html

**Comment by cmoulliard** [comment]
Fixed : https://github.com/snowdrop/component-operator-demo/commit/e5df86ea68bcc836e09126a5e21f5accacf8a20d

Can you retest please @quintesse ?

**Comment by quintesse** [comment]
Works great now. Thanks!
