### ISSUE TITLE
zz_generated.deepcopy.go not generated locally

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/component-operator#43]
### Issue

The script `./script/update-gen.sh` generates a new `zz_generated.deepcopy.go` but within the $GOPATH project and not locally

```
ls -la $GOPATH/src/github.com/snowdrop/component-operator/pkg/apis/component/v1alpha2/zz_generated.deepcopy.go
-rw-r--r--  1 dabou  staff  10604 May 16 06:45 /Users/dabou/Code/go-workspace/src/github.com/snowdrop/component-operator/pkg/apis/component/v1alpha2/zz_generated.deepcopy.go

pwd
/Users/dabou/Code/snowdrop/component-operator
```

**Comment by metacosm** [comment]
k8s `code-generator` only works for project in `$GOPATH` at the moment so this is expected. Modifications have been made to be able to build the project when checked-out in `$GOPATH`

**Comment by cmoulliard** [comment]
I will then update the script to copy the file generated from $GOPATH/..../zz_generated.deepcopy.go within the current directory
