### ISSUE TITLE
Add Build spec

### ISSUE THREAD

**Issue by aureamunoz** [snowdrop/component-operator#69]
Which git uri should be read for filling the BuildSpec.uri? @cmoulliard 
Is `remote.origin.url` oK?

**Comment by cmoulliard** [comment]
> Is `remote.origin.url` oK?

Yes. I suppose that this git field corresponds to the url that you can copy/paste from a Github repo ?

**Comment by aureamunoz** [comment]
Yes, absolutly `https://github.com/ap4k/ap4k.git`
